### ISSUE TITLE
Executing problem with SMT, MILP and SAT

### ISSUE THREAD

**Issue by kavyasreegudisinti** [hadipourh/autoguess#4]
Dear Author,

I have installed the tools using method 3, while executing the SMT, MILP and SAT command i am getting errors. I tried without sudo command 

python3 autoguess.py --inputfile ciphers/Example1/relationfile.txt --solver smt --maxguess 2 --maxsteps 5

/home/.local/lib/python3.10/site-packages/pysmt/smtlib/parser/__init__.py:83: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "/home/tools/autoguess/autoguess.py", line 211, in <module>
    main()
  File "/home/tools/autoguess/autoguess.py", line 208, in main
    startsearch(params)
  File "/home/tools/autoguess/autoguess.py", line 28, in startsearch
    search.search_using_smt(tool_parameters)
  File "/home/tools/autoguess/core/search.py", line 98, in search_using_smt
    from core.gdsmt import ReduceGDtoSMT
  File "/home/tools/autoguess/core/gdsmt.py", line 12, in <module>
    from pysmt.shortcuts import TRUE, Symbol, BVAdd, BVAnd, BVOr, BVMul, BVULE, BVZExt, Solver, types, BV, Equals, write_smtlib
  File "/home/kavya/.local/lib/python3.10/site-packages/pysmt/shortcuts.py", line 38, in <module>
    import pysmt.smtlib.parser
  File "/home/kavya/.local/lib/python3.10/site-packages/pysmt/smtlib/parser/__init__.py", line 91, in <module>
    so_path = pyximport.build_module(name, path,
AttributeError: module 'pyximport' has no attribute 'build_module'
/home/.local/lib/python3.10/site-packages/pysmt/smtlib/parser/__init__.py:83: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "/home/tools/autoguess/autoguess.py", line 211, in <module>
    main()
  File "/home/tools/autoguess/autoguess.py", line 208, in main
    startsearch(params)
  File "/home/tools/autoguess/autoguess.py", line 28, in startsearch
    search.search_using_smt(tool_parameters)
  File "/home/tools/autoguess/core/search.py", line 98, in search_using_smt
    from core.gdsmt import ReduceGDtoSMT
  File "/home/tools/autoguess/core/gdsmt.py", line 12, in <module>
    from pysmt.shortcuts import TRUE, Symbol, BVAdd, BVAnd, BVOr, BVMul, BVULE, BVZExt, Solver, types, BV, Equals, write_smtlib
  File "/home/kavya/.local/lib/python3.10/site-packages/pysmt/shortcuts.py", line 38, in <module>
    import pysmt.smtlib.parser
  File "/home/kavya/.local/lib/python3.10/site-packages/pysmt/smtlib/parser/__init__.py", line 91, in <module>
    so_path = pyximport.build_module(name, path,
AttributeError: module 'pyximport' has no attribute 'build_module

with sudo command 

sudo python3 autoguess.py --inputfile ciphers/Example1/relationfile.txt --solver smt --maxguess 2 --maxsteps 5
Traceback (most recent call last):
  File "/home/tools/autoguess/autoguess.py", line 211, in <module>
    main()
  File "/home/tools/autoguess/autoguess.py", line 208, in main
    startsearch(params)
  File "/home/tools/autoguess/autoguess.py", line 28, in startsearch
    search.search_using_smt(tool_parameters)
  File "/home/tools/autoguess/core/search.py", line 98, in search_using_smt
    from core.gdsmt import ReduceGDtoSMT
  File "/home/tools/autoguess/core/gdsmt.py", line 12, in <module>
    from pysmt.shortcuts import TRUE, Symbol, BVAdd, BVAnd, BVOr, BVMul, BVULE, BVZExt, Solver, types, BV, Equals, write_smtlib
ModuleNotFoundError: No module named 'pysmt'

**Comment by hadipourh** [comment]
Hi,

Thanks for your interest in our tool.

- First of all, we recommend not running Python tools with the `sudo` command. When you run a Python tool with `sudo`, your system may use another version of Python if you have multiple installations. As a result, it might use a Python version for which you have not installed `pysmt`, `pysat`, etc.
- I have checked the third method of installation in a clean system, and it works.

- Regarding the first error, it seems to be related to the `pysmt` module on your system, not `Autoguess`. The issue is likely due to an incompatibility between the Python version and the modules you are using. I recommend trying the installation again, but this time on a clean system. Please report back here if you encounter any further errors. Also, during the installation of Python modules, it's best to avoid using the `sudo` command.

Hope this information helps.
